name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: 22}
      - run: npm install
      - run: npm run build
        env:
          VITE_API_BASE_URL: https://sur-swag-backend.surnswag2.workers.dev
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 488a8034477677c405fd7f66ee013c24
          command: pages deploy dist --project-name sur-swag --branch main
